config {
  type: "table",
  schema: "stg_byx",
  name: "contract_fundoclientecontrato",
  tags: ["staging"]
}

/*
  STAGING — contract_fundoclientecontrato
  Tipagem + limpeza da camada RAW (tudo STRING)
*/

SELECT
  SAFE_CAST(id AS INT64) AS id,
  nome,
  slug,

  -- DATETIME com SAFE_CAST para evitar erros
  SAFE_CAST(dtAtualizacao AS DATETIME) AS dtAtualizacao,
  SAFE_CAST(dtCriacao AS DATETIME) AS dtCriacao,

  db_name

FROM `byx-data-prod.sparrow_consolidado.contract_fundoclientecontrato`

